#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: mlkem-rust-libcrux
  description: portable ML-KEM implementation with some optimizations for AVX2. Full AVX2 support will be added over the coming months. The code is formally verified for panic freedom, correctness, and secret independence in F* using the hax toolchain.
  homepage: https://github.com/pq-code-package/mlkem-rust-libcrux
  default_branch: main
  has_downloads: false
  has_issues: true
  has_projects: true
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
